# Generated by Django 3.2.7 on 2021-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='image')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('imdb_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IMDB rating ')),
                ('pg_rate', models.IntegerField(blank=True, null=True, verbose_name='PG rate ')),
                ('time_long', models.IntegerField(blank=True, null=True, verbose_name='Time long')),
                ('description', models.TextField(verbose_name='description')),
                ('starring', models.CharField(max_length=200, verbose_name='Starring')),
                ('Genres', models.CharField(choices=[('Action', 'ACTION'), ('Animation', 'ANIMATION'), ('Horror', 'HORROR')], max_length=10, verbose_name='genres')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Sliders',
                'verbose_name_plural': 'Sliderss',
            },
        ),
    ]
