# Generated by Django 3.2.7 on 2021-09-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliders',
            name='logo_image',
        ),
    ]
