# Generated by Django 3.2.7 on 2021-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_remove_sliders_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='movie_trailor',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
